### ISSUE TITLE
Do not generate docker images on every CI run

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1453]
When either the dockerfile or the presets change should be enough.

**Comment by provokateurin** [comment]
To make it work with the workflow that generates the preset update PRs it should only run on the main branch and using the dispatch feature (so manually in case some images are broken again).

**Comment by provokateurin** [comment]
This could be implemented a lot easier by just checking if the nextcloud package is in the glob or not because only for that package we need the presets. In addition to that the images could also be built of the nextcloud_test package was updated because it is the source, but that requires some changes because it doesn't have any tests and won't ever be included in the glob.
