### ISSUE TITLE
Support endpoints with password confirmation

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1492]
To use those endpoints the password has to be entered by the user and sent to https://github.com/nextcloud/server/blob/1612d025cf21ac0ae70327c46dd59be66c096627/core/Controller/LoginController.php#L362.
This endpoint is currently not reachable for us and we would need to support CSRF endpoints too (which is some more work).
The better approach would probably be to open up the endpoint and allow us to use it.

**Comment by provokateurin** [comment]
Let's see where this goes https://github.com/nextcloud/server/pull/43000

**Comment by provokateurin** [comment]
Ok, so this is actually a bug in the server auth logic. I will make a fix and then we have to wait for new releases of all the versions we support :/

**Comment by bigcat88** [comment]
I always thought this behavior was intended since we already get a lot of requests from clients who are afraid to use `app_password`.
This change will scare them even more.

Imagine the situation:

You create an application password for the file sync client and you are an administrator.
These changes will allow the application to send your application password somewhere, and the hacker will be able to create a new user with admin rights and covertly act on their behalf from another location.
Without support for API scopes, this change is dangerous.


Do you have any thoughts on this @nickvergessen as you already accepted it?

**Comment by provokateurin** [comment]
In the end we went with https://github.com/nextcloud/server/pull/43668.
We will have to handle the errors in a generic way to display the dialog to do the password confirmation. On unsupported versions we will just have to say that it is not possible to execute the action.

**Comment by Leptopoda** [comment]
Is there any way we can unblock this?
You meant that it is only an issue when sending cookies; we should be able to patch our client to not send them (at least on non web platforms).

I think #1580 should make this really easy.

**Comment by provokateurin** [comment]
This can be implemented now (but only on 29+)

**Comment by provokateurin** [comment]
I thought this would be not so easy to implement, but we can simply assume that only API endpoints called within wrapAction can trigger the password confirmation. We can simply catch the error there and show the dialog and afterwards retry. I first thought it would be necessary to mess around with the RequestManager so it also supports password confirmation for the cached endpoints, but that is simply not required.

**Comment by provokateurin** [comment]
Actually done already, just not in the framework so far (I'm working on it).
