### ISSUE TITLE
Investigate mimetype -> icon mapping

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#437]
NC allows the user to add custom file extension to mimetype mappings. This can be useful for newer or custom file extensions.
file_icons should be able to render icons for a given mimetype (assuming that NC is correctly mapping file extensions -> mimetype).

https://docs.nextcloud.com/server/latest/admin_manual/configuration_mimetypes/index.html
https://github.com/nextcloud/server/blob/master/resources/config/mimetypemapping.dist.json

**Comment by provokateurin** [comment]
The icons seem to be in https://github.com/nextcloud/server/tree/master/core/img/filetypes

**Comment by Leptopoda** [comment]
The parsing of what to fetch happens in:
https://github.com/nextcloud/server/blob/646dfd2a40aa79b8fed8be314070bb8f629a6edc/core/js/mimetype.js

And maybe relevant to understand it:
https://github.com/nextcloud/server/blob/646dfd2a40aa79b8fed8be314070bb8f629a6edc/core/js/mimetypelist.js

The parser is actually more primitive than I expected 🫣

**Comment by Leptopoda** [comment]
I'm also fine with our icons with some better (dynamic) mapping.

**Comment by provokateurin** [comment]
Since https://github.com/nextcloud/server/commit/28725c46a84db6e733c42e38cbc5e1b7f0e3854b we can just rely on the server to give us an icon in case there is no preview available.
I think this makes the files_icons package pretty much obsolete and will make our icons aligned with the server which looks more familiar to users.
