### ISSUE TITLE
Nextcloud package class prefix

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#794]
Split nextcloud package so apps can only import the things they need

**Comment by provokateurin** [comment]
https://github.com/nextcloud/neon/pull/869 addresses this mostly, but we still need to drop the class prefixes so this issue is still relevant after the PR is merged.

**Comment by provokateurin** [comment]
Sadly this is not possible directly because we are lacking support for https://github.com/dart-lang/language/issues/2254. Without this we get clashing names for common classes like Client.

If we decide to break the API we can do it, but then everyone needs to do `import 'package:nextcloud/core.dart' as core;` and so on. Then we need to directly depend on the nextcloud package and remove the `package:neon/nextcloud.dart` export. For me this would be fine, not sure what you think.

**Comment by provokateurin** [comment]
Using the export makes it some places uglier because variable names like `notifications` or `notes` are not allowed anymore and we use them a few times.

**Comment by Leptopoda** [comment]
This would also encourage other people to only import the client they need.

I'm fine with it.

**Comment by provokateurin** [comment]
Although some changes will not be nice the overall improvements are not deniable
